export const COLLABORA_MIME_TYPES = [
	'application/vnd.oasis.opendocument.text',
	'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	'application/vnd.ms-word.document.macroEnabled.12',
	'application/msword',
	'text/rtf',
	'application/vnd.oasis.opendocument.spreadsheet',
	'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	'application/vnd.ms-excel',
	'application/vnd.ms-excel.sheet.macroEnabled.12',
	'text/csv',
	'application/vnd.oasis.opendocument.presentation',
	'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	'application/vnd.ms-powerpoint',
	'application/vnd.oasis.opendocument.graphics',
	'application/vnd.visio',
	'text/plain',
	'text/markdown'
]
